### PR TITLE
fix: disable connect polardbx

### LINKED ISSUE #198: [Improvement]Disable kbcli cluster connect polardbx
kbcli 8.0 should disable the support to connect to polardbx as kbcli 7.2 did
```
➜  ~ kbcli72 version
Kubernetes: v1.27.3-gke.100
KubeBlocks: 0.8.0-beta.42
kbcli: 0.7.2
WARNING: version difference between kbcli (0.7.2) and kubeblocks (0.8.0-beta.42)
➜  ~ kbcli72 cluster connect polardbx-ydsyte
Connect to instance polardbx-ydsyte-gms-0
error: unsupported engine type: polardbx
➜  ~ kbcli version
Kubernetes: v1.27.3-gke.100
KubeBlocks: 0.8.0-beta.42
kbcli: 0.8.0-beta.37
WARNING: version difference between kbcli (0.8.0-beta.37) and kubeblocks (0.8.0-beta.42)
➜  ~ kbcli cluster connect polardbx-ydsyte
Connect to instance polardbx-ydsyte-gms-0
Defaulted container "engine" out of: engine, exporter, kb-role-probe, action-0, tools-updater (init), role-agent-installer (init)
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
command terminated with exit code 1
➜  ~
```

### PR DESCRIPTION
**Pull request by 1aal**
- fix #198

### CODE REVIEW

File: pkg/cmd/cluster/connect.go [hunk 1]
```diff
@@ -74,6 +74,10 @@ var connectExample = templates.Examples(`
 
 const passwordMask = "******"
 
+var kbcliEnginesBlackList = []string{
```
Comment (ldming) [inline pkg/cmd/cluster/connect.go:77]: Suggest naming it `nonConnectiveEngines`.

File: pkg/cmd/cluster/connect.go [hunk 2]
```diff
@@ -74,6 +74,10 @@ var connectExample = templates.Examples(`
...
+	string(models.PolarDBX),
```
Comment (ldming) [inline pkg/cmd/cluster/connect.go:78]: https://github.com/apecloud/kbcli/issues/180  kbcli do not support connect to starrocks, may be add it to this list.

**Review by ldming — APPROVED** [review]
